// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvnoLLd7qHA27HZAXCcMF7V7POMwMIuTo',
    appId: '1:833834196869:web:cb47ea5c882ba3868e6eec',
    messagingSenderId: '833834196869',
    projectId: 'juyoungportfolio-b65cb',
    authDomain: 'juyoungportfolio-b65cb.firebaseapp.com',
    databaseURL: 'https://juyoungportfolio-b65cb.firebaseio.com',
    storageBucket: 'juyoungportfolio-b65cb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ2ab6m3sxkki1_Joc3mvODpS6QWnwirQ',
    appId: '1:833834196869:android:5d7affe25511a5f68e6eec',
    messagingSenderId: '833834196869',
    projectId: 'juyoungportfolio-b65cb',
    databaseURL: 'https://juyoungportfolio-b65cb.firebaseio.com',
    storageBucket: 'juyoungportfolio-b65cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4TE2MdHn-PzHp3OaxoRYc9wLu4HxSaN0',
    appId: '1:833834196869:ios:60ff5dd9cfdbde478e6eec',
    messagingSenderId: '833834196869',
    projectId: 'juyoungportfolio-b65cb',
    databaseURL: 'https://juyoungportfolio-b65cb.firebaseio.com',
    storageBucket: 'juyoungportfolio-b65cb.appspot.com',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4TE2MdHn-PzHp3OaxoRYc9wLu4HxSaN0',
    appId: '1:833834196869:ios:032db0b0337152138e6eec',
    messagingSenderId: '833834196869',
    projectId: 'juyoungportfolio-b65cb',
    databaseURL: 'https://juyoungportfolio-b65cb.firebaseio.com',
    storageBucket: 'juyoungportfolio-b65cb.appspot.com',
    iosBundleId: 'com.example.testProject.RunnerTests',
  );
}
